# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-22 19:09
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=32, verbose_name='\uce74\ud14c\uace0\ub9ac \uba85')),
                ('is_view', models.BooleanField(default=False, help_text='\uba54\ub274\ub85c \ud45c\uc2dc\ud560\uc9c0\uc5d0 \ub300\ud55c \uc5ec\ubd80\uc785\ub2c8\ub2e4.', verbose_name='\ud45c\uc2dc')),
            ],
            options={
                'db_table': 'category',
                'verbose_name': '\uce74\ud14c\uace0\ub9ac \ubaa9\ub85d',
                'verbose_name_plural': '\uce74\ud14c\uace0\ub9ac \ubaa9\ub85d',
            },
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.IntegerField(db_index=True, primary_key=True, serialize=False)),
                ('is_view', models.BooleanField(default=False, help_text='\uc9c4\uc5f4\uc744 \uccb4\ud06c\ud558\uc9c0 \uc54a\uc73c\uba74, \uc720\uc800\uc5d0\uac8c \ub178\ucd9c\ub418\uc9c0 \uc54a\uc2b5\ub2c8\ub2e4.', verbose_name='\uc9c4\uc5f4 \uc5ec\ubd80')),
                ('title', models.CharField(blank=True, db_index=True, default='', max_length=64, verbose_name='\uc81c\ubaa9')),
                ('reg_time', models.DateTimeField(verbose_name='\ub4f1\ub85d\uc2dc\uac04')),
                ('mod_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'content',
                'verbose_name': '\uac8c\uc2dc\uae00',
                'verbose_name_plural': '\uac8c\uc2dc\uae00 \ubaa9\ub85d',
            },
        ),
        migrations.CreateModel(
            name='ContentCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_order', models.PositiveSmallIntegerField(blank=True, default=0, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ft_admin.Category')),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ft_admin.Content')),
            ],
            options={
                'ordering': ('display_order',),
                'db_table': 'content_category',
                'verbose_name_plural': '\ucf58\ud150\uce20 \uce74\ud14c\uace0\ub9ac',
            },
        ),
        migrations.CreateModel(
            name='ContentDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary_desc', models.TextField(blank=True, default='', verbose_name='\uc694\uc57d\uae00')),
                ('detail_desc', ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='', help_text='\uc0ac\uc9c4 \ucd94\uac00 \ubc29\ubc95\uc740: \uc0ac\uc9c4 -> \uc5c5\ub85c\ub4dc -> \ud30c\uc77c \uc120\ud0dd \ud6c4 -> \uc11c\ubc84\ub85c \uc804\uc1a1 -> \ud655\uc778', verbose_name='\ubcf8\ubb38')),
                ('image_01', models.ImageField(blank=True, default=None, upload_to='%Y/%m/%d', verbose_name='\uc378\ub124\uc77c \uc774\ubbf8\uc9c0')),
                ('content', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ft_admin.Content')),
            ],
            options={
                'db_table': 'content_detail',
                'verbose_name': '\ucee8\ud150\uce20 \uc0c1\uc138 \uc124\uba85',
                'verbose_name_plural': '\ucee8\ud150\uce20 \uc0c1\uc138 \uc124\uba85',
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(db_index=True, max_length=64, verbose_name='\uc774\uba54\uc77c \uc8fc\uc18c')),
                ('job', models.CharField(max_length=32, verbose_name='\uc9c1\uc5c5')),
                ('age', models.PositiveSmallIntegerField(verbose_name='\ub098\uc774')),
                ('is_drop_member', models.BooleanField(default=0, verbose_name='\ud0c8\ud1f4 \uc5ec\ubd80')),
                ('reg_time', models.DateTimeField(auto_now_add=True, verbose_name='\uad6c\ub3c5 \uc2e0\uccad\uc77c')),
                ('mod_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'member',
                'verbose_name': '\ud68c\uc6d0',
                'verbose_name_plural': '\ud68c\uc6d0',
            },
        ),
        migrations.AlterUniqueTogether(
            name='contentcategory',
            unique_together=set([('category', 'content')]),
        ),
    ]
