# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-11 06:06
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_order', models.PositiveSmallIntegerField(blank=True, default=0, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ft_admin.Categories')),
            ],
            options={
                'db_table': 'content_category',
                'verbose_name_plural': '\uc0c1\ud488 \uce74\ud14c\uace0\ub9ac',
            },
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_view', models.BooleanField(default=False, help_text='\uc9c4\uc5f4\uc744 \uccb4\ud06c\ud558\uc9c0 \uc54a\uc73c\uba74, \uc720\uc800\uc5d0\uac8c \ub178\ucd9c\ub418\uc9c0 \uc54a\uc2b5\ub2c8\ub2e4.', verbose_name='\uc9c4\uc5f4 \uc5ec\ubd80')),
                ('title', models.CharField(blank=True, db_index=True, default='', max_length=64, verbose_name='\uc81c\ubaa9')),
                ('reg_time', models.DateTimeField(auto_now_add=True)),
                ('mod_time', models.DateTimeField(auto_now=True)),
                ('summary_desc', models.CharField(blank=True, default='', max_length=256, verbose_name='\uc694\uc57d\uc124\uba85')),
                ('simplicity_desc', models.TextField(blank=True, default='', help_text='\uce74\ud39824\uc5d0\uc11c \ucc98\ub7fc \ucd94\uac00\ub85c \ud544\ub4dc\uac00 \ud544\uc694\ud558\uc2dc\uba74 \ud574\ub2f9 "\uac04\ub7b5\uc124\uba85"\uc5d0 \uc785\ub825\ud558\uc138\uc694.', verbose_name='\uac04\ub7b5\uc124\uba85')),
                ('detail_desc', ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='', help_text='\uc0ac\uc9c4 \ucd94\uac00 \ubc29\ubc95\uc740: \uc0ac\uc9c4 -> \uc5c5\ub85c\ub4dc -> \ud30c\uc77c \uc120\ud0dd \ud6c4 -> \uc11c\ubc84\ub85c \uc804\uc1a1 -> \ud655\uc778', verbose_name='\uc0c1\uc138\uc124\uba85')),
                ('image_01', models.ImageField(blank=True, default=None, null=True, upload_to='%Y/%m/%d', verbose_name='\uc0c1\uc138 \uc774\ubbf8\uc9c0')),
                ('image_02', models.ImageField(blank=True, default=None, null=True, upload_to='%Y/%m/%d', verbose_name='\ubaa9\ub85d \uc774\ubbf8\uc9c0')),
                ('image_03', models.ImageField(blank=True, default=None, null=True, upload_to='%Y/%m/%d', verbose_name='\uc791\uc740\ubaa9\ub85d \uc774\ubbf8\uc9c0')),
                ('image_04', models.ImageField(blank=True, default=None, null=True, upload_to='%Y/%m/%d', verbose_name='\ucd95\uc18c \uc774\ubbf8\uc9c0')),
            ],
            options={
                'db_table': 'content',
                'verbose_name': '\uac8c\uc2dc\uae00',
                'verbose_name_plural': '\uac8c\uc2dc\uae00 \ubaa9\ub85d',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('text', models.CharField(max_length=200, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='categories',
            name='content',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ft_admin.Content'),
        ),
        migrations.AlterUniqueTogether(
            name='categories',
            unique_together=set([('category', 'content')]),
        ),
    ]
