# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-22 19:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ft_admin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=32, verbose_name='\uce74\ud14c\uace0\ub9ac \uba85'),
        ),
    ]
