# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-11 09:26
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ft_admin', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='image_02',
        ),
        migrations.RemoveField(
            model_name='content',
            name='image_03',
        ),
        migrations.RemoveField(
            model_name='content',
            name='image_04',
        ),
        migrations.RemoveField(
            model_name='content',
            name='simplicity_desc',
        ),
        migrations.AlterField(
            model_name='content',
            name='detail_desc',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='', help_text='\uc0ac\uc9c4 \ucd94\uac00 \ubc29\ubc95\uc740: \uc0ac\uc9c4 -> \uc5c5\ub85c\ub4dc -> \ud30c\uc77c \uc120\ud0dd \ud6c4 -> \uc11c\ubc84\ub85c \uc804\uc1a1 -> \ud655\uc778', verbose_name='\ubcf8\ubb38'),
        ),
        migrations.AlterField(
            model_name='content',
            name='image_01',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='%Y/%m/%d', verbose_name='\uc378\ub124\uc77c \uc774\ubbf8\uc9c0'),
        ),
        migrations.AlterField(
            model_name='content',
            name='reg_time',
            field=models.DateTimeField(verbose_name='\ub4f1\ub85d\uc2dc\uac04'),
        ),
        migrations.AlterField(
            model_name='content',
            name='summary_desc',
            field=models.TextField(blank=True, default='', verbose_name='\uc694\uc57d\uae00'),
        ),
    ]
