# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-27 09:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ft_admin', '0002_auto_20180123_0417'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='good_job',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='content',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
