# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-11 13:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ft_admin', '0002_auto_20180111_1826'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=32, verbose_name='\uce74\ud14c\uace0\ub9ac \uba85')),
                ('type', models.SmallIntegerField(choices=[(0, '\ub300\ubd84\ub958'), (1, '\uc911\ubd84\ub958'), (2, '\uc18c\ubd84\ub958'), (3, '\uc0c1\uc138\ubd84\ub958')], default=0, verbose_name='\ubd84\ub958')),
                ('is_view', models.BooleanField(default=False, help_text='\uba54\ub274\ub85c \ud45c\uc2dc\ud560\uc9c0\uc5d0 \ub300\ud55c \uc5ec\ubd80\uc785\ub2c8\ub2e4.', verbose_name='\ud45c\uc2dc')),
                ('parent_category', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='ft_admin.Category', verbose_name='\uc0c1\uc704 \uce74\ud14c\uace0\ub9ac')),
            ],
            options={
                'db_table': 'category',
                'verbose_name': '\uc0c1\ud488 \uce74\ud14c\uace0\ub9ac',
                'verbose_name_plural': '\uc0c1\ud488 \uce74\ud14c\uace0\ub9ac',
            },
        ),
        migrations.CreateModel(
            name='DisplayCategoryInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('desc', models.CharField(max_length=256)),
                ('category', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ft_admin.Category')),
            ],
            options={
                'db_table': 'display_category_info',
            },
        ),
        migrations.RenameModel(
            old_name='Categories',
            new_name='ContentCategory',
        ),
        migrations.AlterModelOptions(
            name='contentcategory',
            options={'ordering': ('display_order',), 'verbose_name_plural': '\uc0c1\ud488 \uce74\ud14c\uace0\ub9ac'},
        ),
        migrations.AlterField(
            model_name='contentcategory',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ft_admin.Category'),
        ),
    ]
