# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-12 09:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ft_admin', '0003_auto_20180111_2231'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': '\uce74\ud14c\uace0\ub9ac \ubaa9\ub85d', 'verbose_name_plural': '\uce74\ud14c\uace0\ub9ac \ubaa9\ub85d'},
        ),
        migrations.AlterModelOptions(
            name='contentcategory',
            options={'ordering': ('display_order',), 'verbose_name_plural': '\uce74\ud14c\uace0\ub9ac & \ucf58\ud150\uce20'},
        ),
    ]
