# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-27 09:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ft_admin', '0003_auto_20180127_1848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='good_job',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
