# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-06 15:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ft_admin', '0004_auto_20180127_1849'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='hit_count',
            field=models.IntegerField(default=0, verbose_name='\uc870\ud68c\uc218'),
        ),
    ]
