# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-07 00:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ft_admin', '0005_content_hit_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='display_order',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
    ]
